function labels = aal_labels_bcn()

labels = ...
{'PrecentralL';
'FrontalSupL';
'FrontalSupOrbL';
'FrontalMidL';
'FrontalMidOrbL' ;
'FrontalInfOperL' ;
'FrontalInfTriL' ;
'FrontalInfOrbL' ;
'RolandicOperL' ;
'SuppMotorAreaL' ;
'OlfactoryL' ;
'FrontalSupMedialL' ;
'FrontalMedOrbL' ;
'RectusL' ;
'InsulaL' ;
'CingulumAntL' ;
'CingulumMidL' ;
'CingulumPostL' ;
'HippocampusL' ;
'ParaHippocampalL' ;
'AmygdalaL' ;
'CalcarineL';
'CuneusL' ;
'LingualL' ;
'OccipitalSupL'; 
'OccipitalMidL' ;
'OccipitalInfL' ;
'FusiformL' ;
'PostcentralL' ;
'ParietalSupL' ;
'ParietalInfL' ;
'SupraMarginalL' ;
'AngularL' ;
'PrecuneusL' ;
'ParacentralLobuleL'; 
'CaudateL';
'PutamenL';
'PallidumL';
'ThalamusL';
'HeschlL';
'TemporalSupL';
'TemporalPoleSupL';
'TemporalMidL';
'TemporalPoleMidL';
'TemporalInfL';
'TemporalInfR';
'TemporalPoleMidR';
'TemporalMidR';
'TemporalPoleSupR';
'TemporalSupR';
'HeschlR';
'ThalamusR';
'PallidumR';
'PutamenR';
'CaudateR';
'ParacentralLobuleR';
'PrecuneusR';
'AngularR';
'SupraMarginalR';
'ParietalInfR';
'ParietalSupR';
'PostcentralR';
'FusiformR';
'OccipitalInfR';
'OccipitalMidR';
'OccipitalSupR';
'LingualR';
'CuneusR';
'CalcarineR';
'AmygdalaR';
'ParaHippocampalR';
'HippocampusR';
'CingulumPostR';
'CingulumMidR';
'CingulumAntR';
'InsulaR';
'RectusR';
'FrontalMedOrbR';
'FrontalSupMedialR';
'OlfactoryR';
'SuppMotorAreaR';
'RolandicOperR';
'FrontalInfOrbR';
'FrontalInfTriR';
'FrontalInfOperR';
'FrontalMidOrbR';
'FrontalMidR';
'FrontalSupOrbR';
'FrontalSupR';
'PrecentralR';}